# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test-java:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: make -C java clean build
      - run:
          name: Test
          command: make -C java test
  build-and-test-go:
    docker:
      - image: cimg/go:1.17.3
    steps:
      - checkout
      - run:
          name: Build
          command: make -C go clean build
      - run:
          name: Test
          command: make -C go test

workflows:
  build-all:
    jobs:
      - build-and-test-java
      - build-and-test-go
